"""phase 1 3 core schema

Revision ID: 6247e614f4a2
Revises: 
Create Date: 2026-08-01 04:32:23.397355
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '6247e614f4a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_rule_sets',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_attendance_rule_sets_effective_period_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_rule_sets')),
    sa.UniqueConstraint('code', 'version', name=op.f('uq_attendance_rule_sets_code'))
    )
    op.create_table('audit_logs',
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('trace_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('before_payload', sa.JSON(), nullable=False),
    sa.Column('after_payload', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_object_id'), 'audit_logs', ['object_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_trace_id'), 'audit_logs', ['trace_id'], unique=False)
    op.create_table('cost_centers',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_centers')),
    sa.UniqueConstraint('code', name=op.f('uq_cost_centers_code'))
    )
    op.create_table('hr_events',
    sa.Column('event_number', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('before_payload', sa.JSON(), nullable=False),
    sa.Column('planned_payload', sa.JSON(), nullable=False),
    sa.Column('actual_payload', sa.JSON(), nullable=False),
    sa.Column('workflow_instance_id', sa.Uuid(), nullable=True),
    sa.Column('related_event_id', sa.Uuid(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_event_id'], ['hr_events.id'], name=op.f('fk_hr_events_related_event_id_hr_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hr_events')),
    sa.UniqueConstraint('event_number', name=op.f('uq_hr_events_event_number'))
    )
    op.create_index(op.f('ix_hr_events_effective_date'), 'hr_events', ['effective_date'], unique=False)
    op.create_index(op.f('ix_hr_events_event_type'), 'hr_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_hr_events_object_id'), 'hr_events', ['object_id'], unique=False)
    op.create_table('job_catalog',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('level_code', sa.String(length=50), nullable=True),
    sa.Column('grade_code', sa.String(length=50), nullable=True),
    sa.Column('class_code', sa.String(length=50), nullable=True),
    sa.Column('sequence_code', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_job_catalog_effective_period_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_catalog')),
    sa.UniqueConstraint('code', name=op.f('uq_job_catalog_code'))
    )
    op.create_table('leave_types',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_types')),
    sa.UniqueConstraint('code', name=op.f('uq_leave_types_code'))
    )
    op.create_table('legal_entities',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('registered_name', sa.String(length=300), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_legal_entities_effective_period_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_entities')),
    sa.UniqueConstraint('code', name=op.f('uq_legal_entities_code'))
    )
    op.create_table('occupancy_rules',
    sa.Column('employee_type_code', sa.String(length=50), nullable=False),
    sa.Column('counts_for_headcount', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_occupancy_rules_effective_period_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_occupancy_rules')),
    sa.UniqueConstraint('employee_type_code', 'effective_from', 'version', name=op.f('uq_occupancy_rules_employee_type_code'))
    )
    op.create_table('organization_types',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_types')),
    sa.UniqueConstraint('code', name=op.f('uq_organization_types_code'))
    )
    op.create_table('organizations',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('code', name=op.f('uq_organizations_code'))
    )
    op.create_table('persons',
    sa.Column('employee_number', sa.String(length=6), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('former_name', sa.String(length=200), nullable=True),
    sa.Column('gender_code', sa.String(length=30), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('nationality_code', sa.String(length=3), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("employee_number IS NULL OR employee_number ~ '^[0-9]{6}$'", name=op.f('ck_persons_employee_number_format')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persons'))
    )
    op.create_index(op.f('ix_persons_display_name'), 'persons', ['display_name'], unique=False)
    op.create_index(op.f('ix_persons_employee_number'), 'persons', ['employee_number'], unique=True)
    op.create_table('snapshot_batches',
    sa.Column('snapshot_type', sa.String(length=30), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('boundary_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rule_version', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_batch_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_batch_id'], ['snapshot_batches.id'], name=op.f('fk_snapshot_batches_parent_batch_id_snapshot_batches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snapshot_batches')),
    sa.UniqueConstraint('snapshot_type', 'boundary_at', 'version', name=op.f('uq_snapshot_batches_snapshot_type'))
    )
    op.create_index(op.f('ix_snapshot_batches_period_month'), 'snapshot_batches', ['period_month'], unique=False)
    op.create_table('workflow_definitions',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('active_version', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_definitions')),
    sa.UniqueConstraint('code', name=op.f('uq_workflow_definitions_code'))
    )
    op.create_table('agreement_relationships',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('agreement_type_code', sa.String(length=50), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=True),
    sa.Column('counterparty_name', sa.String(length=300), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_agreement_relationships_effective_period_order')),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], name=op.f('fk_agreement_relationships_legal_entity_id_legal_entities')),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_agreement_relationships_person_id_persons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agreement_relationships'))
    )
    op.create_index(op.f('ix_agreement_relationships_person_id'), 'agreement_relationships', ['person_id'], unique=False)
    op.create_table('candidates',
    sa.Column('candidate_number', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('contact_payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('linked_person_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['linked_person_id'], ['persons.id'], name=op.f('fk_candidates_linked_person_id_persons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates')),
    sa.UniqueConstraint('candidate_number', name=op.f('uq_candidates_candidate_number'))
    )
    op.create_table('employments',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('employee_type_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('planned_start_date', sa.Date(), nullable=False),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('probation_end_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('end_reason_code', sa.String(length=50), nullable=True),
    sa.Column('contract_legal_entity_id', sa.Uuid(), nullable=True),
    sa.Column('payroll_legal_entity_id', sa.Uuid(), nullable=True),
    sa.Column('social_insurance_legal_entity_id', sa.Uuid(), nullable=True),
    sa.Column('tax_legal_entity_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR end_date >= COALESCE(actual_start_date, planned_start_date)', name=op.f('ck_employments_employment_period_order')),
    sa.ForeignKeyConstraint(['contract_legal_entity_id'], ['legal_entities.id'], name=op.f('fk_employments_contract_legal_entity_id_legal_entities')),
    sa.ForeignKeyConstraint(['payroll_legal_entity_id'], ['legal_entities.id'], name=op.f('fk_employments_payroll_legal_entity_id_legal_entities')),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_employments_person_id_persons')),
    sa.ForeignKeyConstraint(['social_insurance_legal_entity_id'], ['legal_entities.id'], name=op.f('fk_employments_social_insurance_legal_entity_id_legal_entities')),
    sa.ForeignKeyConstraint(['tax_legal_entity_id'], ['legal_entities.id'], name=op.f('fk_employments_tax_legal_entity_id_legal_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employments'))
    )
    op.create_index(op.f('ix_employments_person_id'), 'employments', ['person_id'], unique=False)
    op.create_table('headcount_freezes',
    sa.Column('freeze_type', sa.String(length=20), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_catalog.id'], name=op.f('fk_headcount_freezes_job_id_job_catalog')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_headcount_freezes_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_headcount_freezes'))
    )
    op.create_index(op.f('ix_headcount_freezes_period_month'), 'headcount_freezes', ['period_month'], unique=False)
    op.create_table('headcount_plans',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('planned_count', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('change_reason', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('planned_count >= 0', name=op.f('ck_headcount_plans_planned_count_nonnegative')),
    sa.ForeignKeyConstraint(['job_id'], ['job_catalog.id'], name=op.f('fk_headcount_plans_job_id_job_catalog')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_headcount_plans_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_headcount_plans')),
    sa.UniqueConstraint('organization_id', 'job_id', 'period_month', 'version', name=op.f('uq_headcount_plans_organization_id'))
    )
    op.create_index(op.f('ix_headcount_plans_job_id'), 'headcount_plans', ['job_id'], unique=False)
    op.create_index(op.f('ix_headcount_plans_organization_id'), 'headcount_plans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_headcount_plans_period_month'), 'headcount_plans', ['period_month'], unique=False)
    op.create_table('organization_cost_allocations',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('cost_center_id', sa.Uuid(), nullable=False),
    sa.Column('allocation_percent', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('allocation_percent > 0 AND allocation_percent <= 100', name=op.f('ck_organization_cost_allocations_allocation_percent_range')),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_organization_cost_allocations_effective_period_order')),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], name=op.f('fk_organization_cost_allocations_cost_center_id_cost_centers')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_cost_allocations_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_cost_allocations')),
    sa.UniqueConstraint('organization_id', 'cost_center_id', 'effective_from', 'version', name=op.f('uq_organization_cost_allocations_organization_id'))
    )
    op.create_index(op.f('ix_organization_cost_allocations_organization_id'), 'organization_cost_allocations', ['organization_id'], unique=False)
    op.create_table('organization_legal_entities',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_organization_legal_entities_effective_period_order')),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], name=op.f('fk_organization_legal_entities_legal_entity_id_legal_entities')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_legal_entities_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_legal_entities')),
    sa.UniqueConstraint('organization_id', 'legal_entity_id', 'effective_from', name=op.f('uq_organization_legal_entities_organization_id'))
    )
    op.create_index(op.f('ix_organization_legal_entities_legal_entity_id'), 'organization_legal_entities', ['legal_entity_id'], unique=False)
    op.create_index(op.f('ix_organization_legal_entities_organization_id'), 'organization_legal_entities', ['organization_id'], unique=False)
    op.create_table('organization_person_relations',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.String(length=30), nullable=False),
    sa.Column('bp_type', sa.String(length=10), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_organization_person_relations_effective_period_order')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_person_relations_organization_id_organizations')),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_organization_person_relations_person_id_persons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_person_relations'))
    )
    op.create_index(op.f('ix_organization_person_relations_organization_id'), 'organization_person_relations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_person_relations_person_id'), 'organization_person_relations', ['person_id'], unique=False)
    op.create_table('organization_versions',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('organization_type_id', sa.Uuid(), nullable=False),
    sa.Column('parent_organization_id', sa.Uuid(), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_organization_versions_effective_period_order')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_versions_organization_id_organizations')),
    sa.ForeignKeyConstraint(['organization_type_id'], ['organization_types.id'], name=op.f('fk_organization_versions_organization_type_id_organization_types')),
    sa.ForeignKeyConstraint(['parent_organization_id'], ['organizations.id'], name=op.f('fk_organization_versions_parent_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_versions')),
    sa.UniqueConstraint('organization_id', 'version', name=op.f('uq_organization_versions_organization_id'))
    )
    op.create_index(op.f('ix_organization_versions_organization_id'), 'organization_versions', ['organization_id'], unique=False)
    op.create_table('recruitment_requests',
    sa.Column('request_number', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('target_month', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('workflow_instance_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('requested_count > 0', name=op.f('ck_recruitment_requests_requested_count_positive')),
    sa.ForeignKeyConstraint(['job_id'], ['job_catalog.id'], name=op.f('fk_recruitment_requests_job_id_job_catalog')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_recruitment_requests_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recruitment_requests')),
    sa.UniqueConstraint('request_number', name=op.f('uq_recruitment_requests_request_number'))
    )
    op.create_index(op.f('ix_recruitment_requests_organization_id'), 'recruitment_requests', ['organization_id'], unique=False)
    op.create_table('reporting_relations',
    sa.Column('manager_person_id', sa.Uuid(), nullable=False),
    sa.Column('subordinate_person_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.String(length=20), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_reporting_relations_effective_period_order')),
    sa.CheckConstraint('manager_person_id <> subordinate_person_id', name=op.f('ck_reporting_relations_different_people')),
    sa.ForeignKeyConstraint(['manager_person_id'], ['persons.id'], name=op.f('fk_reporting_relations_manager_person_id_persons')),
    sa.ForeignKeyConstraint(['subordinate_person_id'], ['persons.id'], name=op.f('fk_reporting_relations_subordinate_person_id_persons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reporting_relations'))
    )
    op.create_index(op.f('ix_reporting_relations_manager_person_id'), 'reporting_relations', ['manager_person_id'], unique=False)
    op.create_index(op.f('ix_reporting_relations_subordinate_person_id'), 'reporting_relations', ['subordinate_person_id'], unique=False)
    op.create_table('revenue_targets',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('annual_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('monthly_amounts', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('change_reason', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('annual_amount >= 0', name=op.f('ck_revenue_targets_annual_amount_nonnegative')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_revenue_targets_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revenue_targets')),
    sa.UniqueConstraint('organization_id', 'year', 'currency_code', 'version', name=op.f('uq_revenue_targets_organization_id'))
    )
    op.create_index(op.f('ix_revenue_targets_organization_id'), 'revenue_targets', ['organization_id'], unique=False)
    op.create_table('shifts',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('crosses_midnight', sa.Boolean(), nullable=False),
    sa.Column('rule_set_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_set_id'], ['attendance_rule_sets.id'], name=op.f('fk_shifts_rule_set_id_attendance_rule_sets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts')),
    sa.UniqueConstraint('code', name=op.f('uq_shifts_code'))
    )
    op.create_table('workflow_versions',
    sa.Column('workflow_definition_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('change_reason', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_definition_id'], ['workflow_definitions.id'], name=op.f('fk_workflow_versions_workflow_definition_id_workflow_definitions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_versions')),
    sa.UniqueConstraint('workflow_definition_id', 'version', name=op.f('uq_workflow_versions_workflow_definition_id'))
    )
    op.create_index(op.f('ix_workflow_versions_workflow_definition_id'), 'workflow_versions', ['workflow_definition_id'], unique=False)
    op.create_table('attendance_daily_results',
    sa.Column('employment_id', sa.Uuid(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scheduled_minutes', sa.Integer(), nullable=False),
    sa.Column('worked_minutes', sa.Integer(), nullable=False),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('early_leave_minutes', sa.Integer(), nullable=False),
    sa.Column('exception_codes', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], name=op.f('fk_attendance_daily_results_employment_id_employments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_daily_results')),
    sa.UniqueConstraint('employment_id', 'work_date', 'version', name=op.f('uq_attendance_daily_results_employment_id'))
    )
    op.create_index(op.f('ix_attendance_daily_results_employment_id'), 'attendance_daily_results', ['employment_id'], unique=False)
    op.create_index(op.f('ix_attendance_daily_results_work_date'), 'attendance_daily_results', ['work_date'], unique=False)
    op.create_table('attendance_monthly_results',
    sa.Column('employment_id', sa.Uuid(), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('scheduled_days', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('worked_days', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('leave_days', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('absent_days', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('early_leave_minutes', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], name=op.f('fk_attendance_monthly_results_employment_id_employments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_monthly_results')),
    sa.UniqueConstraint('employment_id', 'period_month', 'version', name=op.f('uq_attendance_monthly_results_employment_id'))
    )
    op.create_index(op.f('ix_attendance_monthly_results_employment_id'), 'attendance_monthly_results', ['employment_id'], unique=False)
    op.create_index(op.f('ix_attendance_monthly_results_period_month'), 'attendance_monthly_results', ['period_month'], unique=False)
    op.create_table('attendance_punches',
    sa.Column('employment_id', sa.Uuid(), nullable=False),
    sa.Column('punched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('punch_type', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], name=op.f('fk_attendance_punches_employment_id_employments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_punches')),
    sa.UniqueConstraint('source', 'source_record_id', name=op.f('uq_attendance_punches_source'))
    )
    op.create_index(op.f('ix_attendance_punches_employment_id'), 'attendance_punches', ['employment_id'], unique=False)
    op.create_index(op.f('ix_attendance_punches_punched_at'), 'attendance_punches', ['punched_at'], unique=False)
    op.create_table('contract_records',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('employment_id', sa.Uuid(), nullable=True),
    sa.Column('contract_type_code', sa.String(length=50), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metadata_payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_contract_records_effective_period_order')),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], name=op.f('fk_contract_records_employment_id_employments')),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], name=op.f('fk_contract_records_legal_entity_id_legal_entities')),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_contract_records_person_id_persons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract_records')),
    sa.UniqueConstraint('contract_number', name=op.f('uq_contract_records_contract_number'))
    )
    op.create_index(op.f('ix_contract_records_person_id'), 'contract_records', ['person_id'], unique=False)
    op.create_table('employment_assignments',
    sa.Column('employment_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('relation_type', sa.String(length=30), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_event_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_employment_assignments_effective_period_order')),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], name=op.f('fk_employment_assignments_employment_id_employments')),
    sa.ForeignKeyConstraint(['job_id'], ['job_catalog.id'], name=op.f('fk_employment_assignments_job_id_job_catalog')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_employment_assignments_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employment_assignments'))
    )
    op.create_index(op.f('ix_employment_assignments_employment_id'), 'employment_assignments', ['employment_id'], unique=False)
    op.create_index(op.f('ix_employment_assignments_organization_id'), 'employment_assignments', ['organization_id'], unique=False)
    op.create_table('headcount_snapshots',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('headcount_plan_id', sa.Uuid(), nullable=True),
    sa.Column('person_count', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['snapshot_batches.id'], name=op.f('fk_headcount_snapshots_batch_id_snapshot_batches')),
    sa.ForeignKeyConstraint(['headcount_plan_id'], ['headcount_plans.id'], name=op.f('fk_headcount_snapshots_headcount_plan_id_headcount_plans')),
    sa.ForeignKeyConstraint(['job_id'], ['job_catalog.id'], name=op.f('fk_headcount_snapshots_job_id_job_catalog')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_headcount_snapshots_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_headcount_snapshots')),
    sa.UniqueConstraint('batch_id', 'organization_id', 'job_id', name=op.f('uq_headcount_snapshots_batch_id'))
    )
    op.create_index(op.f('ix_headcount_snapshots_batch_id'), 'headcount_snapshots', ['batch_id'], unique=False)
    op.create_table('job_applications',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('recruitment_request_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('offer_payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_job_applications_candidate_id_candidates')),
    sa.ForeignKeyConstraint(['recruitment_request_id'], ['recruitment_requests.id'], name=op.f('fk_job_applications_recruitment_request_id_recruitment_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_applications')),
    sa.UniqueConstraint('candidate_id', 'recruitment_request_id', name=op.f('uq_job_applications_candidate_id'))
    )
    op.create_index(op.f('ix_job_applications_candidate_id'), 'job_applications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_job_applications_recruitment_request_id'), 'job_applications', ['recruitment_request_id'], unique=False)
    op.create_table('schedule_assignments',
    sa.Column('employment_id', sa.Uuid(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('shift_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], name=op.f('fk_schedule_assignments_employment_id_employments')),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_schedule_assignments_shift_id_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_assignments')),
    sa.UniqueConstraint('employment_id', 'work_date', name=op.f('uq_schedule_assignments_employment_id'))
    )
    op.create_index(op.f('ix_schedule_assignments_employment_id'), 'schedule_assignments', ['employment_id'], unique=False)
    op.create_index(op.f('ix_schedule_assignments_work_date'), 'schedule_assignments', ['work_date'], unique=False)
    op.create_table('workflow_instances',
    sa.Column('instance_number', sa.String(length=50), nullable=False),
    sa.Column('workflow_version_id', sa.Uuid(), nullable=False),
    sa.Column('business_object_type', sa.String(length=50), nullable=False),
    sa.Column('business_object_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_node_code', sa.String(length=80), nullable=True),
    sa.Column('started_by', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['workflow_versions.id'], name=op.f('fk_workflow_instances_workflow_version_id_workflow_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_instances')),
    sa.UniqueConstraint('instance_number', name=op.f('uq_workflow_instances_instance_number'))
    )
    op.create_index(op.f('ix_workflow_instances_business_object_id'), 'workflow_instances', ['business_object_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('request_number', sa.String(length=50), nullable=False),
    sa.Column('employment_id', sa.Uuid(), nullable=False),
    sa.Column('leave_type_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('workflow_instance_id', sa.Uuid(), nullable=True),
    sa.Column('cancellation_of_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_leave_requests_leave_amount_positive')),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_leave_requests_leave_period_order')),
    sa.ForeignKeyConstraint(['cancellation_of_id'], ['leave_requests.id'], name=op.f('fk_leave_requests_cancellation_of_id_leave_requests')),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], name=op.f('fk_leave_requests_employment_id_employments')),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], name=op.f('fk_leave_requests_leave_type_id_leave_types')),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instances.id'], name=op.f('fk_leave_requests_workflow_instance_id_workflow_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_requests')),
    sa.UniqueConstraint('request_number', name=op.f('uq_leave_requests_request_number'))
    )
    op.create_index(op.f('ix_leave_requests_employment_id'), 'leave_requests', ['employment_id'], unique=False)
    op.create_table('workflow_tasks',
    sa.Column('workflow_instance_id', sa.Uuid(), nullable=False),
    sa.Column('node_code', sa.String(length=80), nullable=False),
    sa.Column('sign_mode', sa.String(length=10), nullable=False),
    sa.Column('assignee_type', sa.String(length=30), nullable=False),
    sa.Column('assignee_ref', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instances.id'], name=op.f('fk_workflow_tasks_workflow_instance_id_workflow_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_tasks'))
    )
    op.create_index(op.f('ix_workflow_tasks_workflow_instance_id'), 'workflow_tasks', ['workflow_instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_tasks_workflow_instance_id'), table_name='workflow_tasks')
    op.drop_table('workflow_tasks')
    op.drop_index(op.f('ix_leave_requests_employment_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_workflow_instances_business_object_id'), table_name='workflow_instances')
    op.drop_table('workflow_instances')
    op.drop_index(op.f('ix_schedule_assignments_work_date'), table_name='schedule_assignments')
    op.drop_index(op.f('ix_schedule_assignments_employment_id'), table_name='schedule_assignments')
    op.drop_table('schedule_assignments')
    op.drop_index(op.f('ix_job_applications_recruitment_request_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_candidate_id'), table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_index(op.f('ix_headcount_snapshots_batch_id'), table_name='headcount_snapshots')
    op.drop_table('headcount_snapshots')
    op.drop_index(op.f('ix_employment_assignments_organization_id'), table_name='employment_assignments')
    op.drop_index(op.f('ix_employment_assignments_employment_id'), table_name='employment_assignments')
    op.drop_table('employment_assignments')
    op.drop_index(op.f('ix_contract_records_person_id'), table_name='contract_records')
    op.drop_table('contract_records')
    op.drop_index(op.f('ix_attendance_punches_punched_at'), table_name='attendance_punches')
    op.drop_index(op.f('ix_attendance_punches_employment_id'), table_name='attendance_punches')
    op.drop_table('attendance_punches')
    op.drop_index(op.f('ix_attendance_monthly_results_period_month'), table_name='attendance_monthly_results')
    op.drop_index(op.f('ix_attendance_monthly_results_employment_id'), table_name='attendance_monthly_results')
    op.drop_table('attendance_monthly_results')
    op.drop_index(op.f('ix_attendance_daily_results_work_date'), table_name='attendance_daily_results')
    op.drop_index(op.f('ix_attendance_daily_results_employment_id'), table_name='attendance_daily_results')
    op.drop_table('attendance_daily_results')
    op.drop_index(op.f('ix_workflow_versions_workflow_definition_id'), table_name='workflow_versions')
    op.drop_table('workflow_versions')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_revenue_targets_organization_id'), table_name='revenue_targets')
    op.drop_table('revenue_targets')
    op.drop_index(op.f('ix_reporting_relations_subordinate_person_id'), table_name='reporting_relations')
    op.drop_index(op.f('ix_reporting_relations_manager_person_id'), table_name='reporting_relations')
    op.drop_table('reporting_relations')
    op.drop_index(op.f('ix_recruitment_requests_organization_id'), table_name='recruitment_requests')
    op.drop_table('recruitment_requests')
    op.drop_index(op.f('ix_organization_versions_organization_id'), table_name='organization_versions')
    op.drop_table('organization_versions')
    op.drop_index(op.f('ix_organization_person_relations_person_id'), table_name='organization_person_relations')
    op.drop_index(op.f('ix_organization_person_relations_organization_id'), table_name='organization_person_relations')
    op.drop_table('organization_person_relations')
    op.drop_index(op.f('ix_organization_legal_entities_organization_id'), table_name='organization_legal_entities')
    op.drop_index(op.f('ix_organization_legal_entities_legal_entity_id'), table_name='organization_legal_entities')
    op.drop_table('organization_legal_entities')
    op.drop_index(op.f('ix_organization_cost_allocations_organization_id'), table_name='organization_cost_allocations')
    op.drop_table('organization_cost_allocations')
    op.drop_index(op.f('ix_headcount_plans_period_month'), table_name='headcount_plans')
    op.drop_index(op.f('ix_headcount_plans_organization_id'), table_name='headcount_plans')
    op.drop_index(op.f('ix_headcount_plans_job_id'), table_name='headcount_plans')
    op.drop_table('headcount_plans')
    op.drop_index(op.f('ix_headcount_freezes_period_month'), table_name='headcount_freezes')
    op.drop_table('headcount_freezes')
    op.drop_index(op.f('ix_employments_person_id'), table_name='employments')
    op.drop_table('employments')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_agreement_relationships_person_id'), table_name='agreement_relationships')
    op.drop_table('agreement_relationships')
    op.drop_table('workflow_definitions')
    op.drop_index(op.f('ix_snapshot_batches_period_month'), table_name='snapshot_batches')
    op.drop_table('snapshot_batches')
    op.drop_index(op.f('ix_persons_employee_number'), table_name='persons')
    op.drop_index(op.f('ix_persons_display_name'), table_name='persons')
    op.drop_table('persons')
    op.drop_table('organizations')
    op.drop_table('organization_types')
    op.drop_table('occupancy_rules')
    op.drop_table('legal_entities')
    op.drop_table('leave_types')
    op.drop_table('job_catalog')
    op.drop_index(op.f('ix_hr_events_object_id'), table_name='hr_events')
    op.drop_index(op.f('ix_hr_events_event_type'), table_name='hr_events')
    op.drop_index(op.f('ix_hr_events_effective_date'), table_name='hr_events')
    op.drop_table('hr_events')
    op.drop_table('cost_centers')
    op.drop_index(op.f('ix_audit_logs_trace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_object_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('attendance_rule_sets')
    # ### end Alembic commands ###

