"""Import all mapped classes so Alembic sees the complete metadata."""

from hris.modules.attendance.models import (
    AttendanceDailyResult,
    AttendanceMonthlyResult,
    AttendancePunch,
    AttendanceRuleSet,
    LeaveRequest,
    LeaveType,
    ScheduleAssignment,
    Shift,
)
from hris.modules.workflow.models import (
    Candidate,
    ContractRecord,
    JobApplication,
    WorkflowDefinition,
    WorkflowInstance,
    WorkflowTask,
    WorkflowVersion,
)
from hris.modules.workforce.models import (
    AgreementRelationship,
    AuditLog,
    CostCenter,
    Employment,
    EmploymentAssignment,
    HeadcountFreeze,
    HeadcountPlan,
    HeadcountSnapshot,
    HrEvent,
    JobCatalog,
    LegalEntity,
    OccupancyRule,
    Organization,
    OrganizationCostAllocation,
    OrganizationLegalEntity,
    OrganizationPersonRelation,
    OrganizationType,
    OrganizationVersion,
    Person,
    RecruitmentRequest,
    ReportingRelation,
    RevenueTarget,
    SnapshotBatch,
)

__all__ = [
    "AgreementRelationship",
    "AttendanceDailyResult",
    "AttendanceMonthlyResult",
    "AttendancePunch",
    "AttendanceRuleSet",
    "AuditLog",
    "Candidate",
    "ContractRecord",
    "CostCenter",
    "Employment",
    "EmploymentAssignment",
    "HeadcountFreeze",
    "HeadcountPlan",
    "HeadcountSnapshot",
    "HrEvent",
    "JobApplication",
    "JobCatalog",
    "LeaveRequest",
    "LeaveType",
    "LegalEntity",
    "OccupancyRule",
    "Organization",
    "OrganizationCostAllocation",
    "OrganizationLegalEntity",
    "OrganizationPersonRelation",
    "OrganizationType",
    "OrganizationVersion",
    "Person",
    "RecruitmentRequest",
    "ReportingRelation",
    "RevenueTarget",
    "ScheduleAssignment",
    "Shift",
    "SnapshotBatch",
    "WorkflowDefinition",
    "WorkflowInstance",
    "WorkflowTask",
    "WorkflowVersion",
]

